# Generated by Django 5.2.7 on 2025-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('enterprise', models.CharField(max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site')),
            ],
        ),
    ]
